/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/gmilliez/openrobots/src/acapela-genom/ros/client/ros/acapela/srv/SetVoice.srv
 *
 */


#ifndef ACAPELA_MESSAGE_SETVOICE_H
#define ACAPELA_MESSAGE_SETVOICE_H

#include <ros/service_traits.h>


#include <acapela/SetVoiceRequest.h>
#include <acapela/SetVoiceResponse.h>


namespace acapela
{

struct SetVoice
{

typedef SetVoiceRequest Request;
typedef SetVoiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVoice
} // namespace acapela


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::acapela::SetVoice > {
  static const char* value()
  {
    return "bce7daab4b8873329d2ffa6101c1e230";
  }

  static const char* value(const ::acapela::SetVoice&) { return value(); }
};

template<>
struct DataType< ::acapela::SetVoice > {
  static const char* value()
  {
    return "acapela/SetVoice";
  }

  static const char* value(const ::acapela::SetVoice&) { return value(); }
};


// service_traits::MD5Sum< ::acapela::SetVoiceRequest> should match 
// service_traits::MD5Sum< ::acapela::SetVoice > 
template<>
struct MD5Sum< ::acapela::SetVoiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::acapela::SetVoice >::value();
  }
  static const char* value(const ::acapela::SetVoiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::acapela::SetVoiceRequest> should match 
// service_traits::DataType< ::acapela::SetVoice > 
template<>
struct DataType< ::acapela::SetVoiceRequest>
{
  static const char* value()
  {
    return DataType< ::acapela::SetVoice >::value();
  }
  static const char* value(const ::acapela::SetVoiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::acapela::SetVoiceResponse> should match 
// service_traits::MD5Sum< ::acapela::SetVoice > 
template<>
struct MD5Sum< ::acapela::SetVoiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::acapela::SetVoice >::value();
  }
  static const char* value(const ::acapela::SetVoiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::acapela::SetVoiceResponse> should match 
// service_traits::DataType< ::acapela::SetVoice > 
template<>
struct DataType< ::acapela::SetVoiceResponse>
{
  static const char* value()
  {
    return DataType< ::acapela::SetVoice >::value();
  }
  static const char* value(const ::acapela::SetVoiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACAPELA_MESSAGE_SETVOICE_H
